export type CONSTANTS = {
	NODE_ENV: string;
	WEBSITE_ADDRESS: string;
	APP_ADDRESS: string;
	ADMIN_ADDRESS: string;
	API_ADDRESS: string;
	SECRET: string;
};

// prettier-ignore
export const ENVS: CONSTANTS = {
  NODE_ENV: process.env.EXPO_PUBLIC_NODE_ENV as CONSTANTS['NODE_ENV'],
  WEBSITE_ADDRESS: process.env.EXPO_PUBLIC_WEBSITE_ADDRESS as CONSTANTS['WEBSITE_ADDRESS'],
  APP_ADDRESS: process.env.EXPO_PUBLIC_APP_ADDRESS as CONSTANTS['APP_ADDRESS'],
  ADMIN_ADDRESS: process.env.EXPO_PUBLIC_ADMIN_ADDRESS as CONSTANTS['ADMIN_ADDRESS'],
  API_ADDRESS: process.env.EXPO_PUBLIC_API_ADDRESS as CONSTANTS['API_ADDRESS'],
  SECRET: process.env.EXPO_PUBLIC_SECRET as CONSTANTS['SECRET'],
};
