export type APP_COLORS = {
  TEXT: string;
  BACKGROUND: string;
  TAB_BAR_BACKGROUND: string;
  TAB_BAR_FOREGROUND: string;
  TINT: string;
  TAB_ICON_DEFAULT: string;
  TAB_ICON_SELECTED: string;
  DISABLED: string;
  DISABLED_TEXT: string;
  DIM: string;
  ICON: string;
  FOREGROUND: string;
  CARD: string;
  CARD_FOREGROUND: string;
  POPOVER: string;
  POPOVER_FOREGROUND: string;
  PRIMARY: string;
  PRIMARY_FOREGROUND: string;
  SECONDARY: string;
  SECONDARY_FOREGROUND: string;
  MUTED: string;
  MUTED_FOREGROUND: string;
  ACCENT: string;
  ACCENT_FOREGROUND: string;
  DESTRUCTIVE: string;
  DESTRUCTIVE_FOREGROUND: string;
  BORDER: string;
  BORDER_DARKER: string;
  INPUT: string;
  INPUT_BACKGROUND: string;
  SWITCH_BACKGROUND: string;
  RING: string;
  CHART_1: string;
  CHART_2: string;
  CHART_3: string;
  CHART_4: string;
  CHART_5: string;
  SIDEBAR: string;
  SIDEBAR_FOREGROUND: string;
  SIDEBAR_PRIMARY: string;
  SIDEBAR_PRIMARY_FOREGROUND: string;
  SIDEBAR_ACCENT: string;
  SIDEBAR_ACCENT_FOREGROUND: string;
  SIDEBAR_BORDER: string;
  SIDEBAR_RING: string;
  BUTTON_PRIMARY_BACKGROUND: string;
  BUTTON_PRIMARY_BACKGROUND_DARK: string;
  BUTTON_PRIMARY_FOREGROUND: string;
  BUTTON_PRIMARY_BORDER: string;
  BUTTON_SECONDARY_BACKGROUND: string;
  BUTTON_SECONDARY_BACKGROUND_DARK: string;
  BUTTON_SECONDARY_FOREGROUND: string;
  BUTTON_SECONDARY_BORDER: string;
  BUTTON_SECONDARY_BORDER_DARK: string;
};

const WHITE = "rgba(255, 255, 255, 1)"; /* #FFFFFF */
const BLACK = "rgba(0, 0, 0, 1)"; /* #000000 */
const BLUE = "rgba(47, 149, 220, 1)"; /* #2F95DC */
const PINK = "rgba(236, 72, 153, 1)"; /* #EC4899 */
const GRAY_300 = "rgba(204, 204, 204, 1)"; /* #CCCCCC */
const GRAY_200 = "rgba(236, 237, 238, 1)"; /* #ECEDEE */
const GRAY_500 = "rgba(115, 119, 128, 1)"; /* #737780 */
const GRAY_700 = "rgba(68, 73, 85, 1)"; /* #444955 */
const GRAY_100 = "rgba(229, 229, 234, 1)"; /* #E5E5EA */
const GRAY_50 = "rgba(242, 242, 247, 1)"; /* #F2F2F7 */
const GRAY_400 = "rgba(142, 142, 147, 1)"; /* #8E8E93 */
const GRAY_350 = "rgba(198, 198, 200, 1)"; /* #C6C6C8 */
const GRAY_10 = "rgba(0,0,0,0.08)"; /* light theme BORDER */
/** Same hue as BORDER (`GRAY_10`), higher opacity — darker line weight for icons. */
const ICON_BORDER_LIGHT = "rgba(0, 0, 0, 0.40)"; /* #000000 */
/** Same family as BORDER (`CHARCOAL_900`), darker for icon strokes. */
const ICON_BORDER_DARK = "rgba(10, 10, 12, 1)"; /* ~darker than #1C1C1E */
const RED_500 = "rgba(255, 59, 48, 1)"; /* #FF3B30 */
const RED_400 = "rgba(255, 69, 58, 1)"; /* #FF453A */
const DARK_NAVY = "rgba(17, 24, 39, 1)"; /* #111827 */
const DIM_BLACK_15 = "rgba(0, 0, 0, 0.15)"; /* #000000 */
const DIM_BLACK_8 = "rgba(0, 0, 0, 0.08)"; /* #000000 */
const CHARCOAL_900 = "rgba(28, 28, 30, 1)"; /* #1C1C1E */
const CHARCOAL_800 = "rgba(44, 44, 46, 1)"; /* #2C2C2E */
const CHARCOAL_700 = "rgba(56, 56, 58, 1)"; /* #38383A */
const GRAY_250 = "rgba(233, 233, 234, 1)"; /* #E9E9EA */
const GRAY_600 = "rgba(235, 235, 245, 1)"; /* #EBEBF5 */
const GRAY_750 = "rgba(57, 57, 61, 1)"; /* #39393D */
const DIM_WHITE_20 = "rgba(255, 255, 255, 0.2)"; /* #FFFFFF */
const DIM_WHITE_8 = "rgba(255, 255, 255, 0.08)"; /* #FFFFFF */
const CHART_1 = "oklch(0.646 0.222 41.116)";
const CHART_2 = "oklch(0.6 0.118 184.704)";
const CHART_3 = "oklch(0.398 0.07 227.392)";
const CHART_4 = "oklch(0.828 0.189 84.429)";
const CHART_5 = "oklch(0.769 0.188 70.08)";

export const COLORS = {
  WHITE,
  BLACK,
  BLUE,
  PINK,
  GRAY_300,
  GRAY_200,
  GRAY_500,
  GRAY_700,
  GRAY_100,
  GRAY_50,
  GRAY_10,
  ICON_BORDER_LIGHT,
  ICON_BORDER_DARK,
  GRAY_400,
  GRAY_350,
  RED_500,
  RED_400,
  DARK_NAVY,
  DIM_BLACK_15,
  DIM_BLACK_8,
  CHARCOAL_900,
  CHARCOAL_800,
  CHARCOAL_700,
  GRAY_250,
  GRAY_600,
  GRAY_750,
  DIM_WHITE_20,
  DIM_WHITE_8,
  CHART_1,
  CHART_2,
  CHART_3,
  CHART_4,
  CHART_5,
};

export const LIGHT_THEME_COLORS: APP_COLORS = {
  TEXT: BLACK,
  BACKGROUND: WHITE,
  TINT: BLUE,
  TAB_BAR_BACKGROUND: BLACK,
  TAB_BAR_FOREGROUND: CHARCOAL_800,
  TAB_ICON_DEFAULT: GRAY_300,
  TAB_ICON_SELECTED: BLUE,
  DISABLED: GRAY_200,
  DISABLED_TEXT: GRAY_500,
  DIM: DIM_BLACK_15,
  ICON: ICON_BORDER_LIGHT,
  FOREGROUND: BLACK,
  CARD: WHITE,
  CARD_FOREGROUND: BLACK,
  POPOVER: WHITE,
  POPOVER_FOREGROUND: BLACK,
  PRIMARY: PINK,
  PRIMARY_FOREGROUND: WHITE,
  SECONDARY: GRAY_100,
  SECONDARY_FOREGROUND: BLACK,
  MUTED: GRAY_50,
  MUTED_FOREGROUND: GRAY_400,
  ACCENT: GRAY_100,
  ACCENT_FOREGROUND: BLACK,
  DESTRUCTIVE: RED_500,
  DESTRUCTIVE_FOREGROUND: WHITE,
  BORDER: GRAY_50,
  BORDER_DARKER: GRAY_250,
  INPUT: GRAY_100,
  INPUT_BACKGROUND: WHITE,
  SWITCH_BACKGROUND: GRAY_250,
  RING: PINK,
  CHART_1,
  CHART_2,
  CHART_3,
  CHART_4,
  CHART_5,
  SIDEBAR: GRAY_50,
  SIDEBAR_FOREGROUND: BLACK,
  SIDEBAR_PRIMARY: PINK,
  SIDEBAR_PRIMARY_FOREGROUND: WHITE,
  SIDEBAR_ACCENT: GRAY_100,
  SIDEBAR_ACCENT_FOREGROUND: BLACK,
  SIDEBAR_BORDER: GRAY_350,
  SIDEBAR_RING: PINK,
  BUTTON_PRIMARY_BACKGROUND: DARK_NAVY,
  BUTTON_PRIMARY_BACKGROUND_DARK: BLACK,
  BUTTON_PRIMARY_FOREGROUND: WHITE,
  BUTTON_PRIMARY_BORDER: DARK_NAVY,
  BUTTON_SECONDARY_BACKGROUND: WHITE,
  BUTTON_SECONDARY_BACKGROUND_DARK: GRAY_100,
  BUTTON_SECONDARY_FOREGROUND: BLACK,
  BUTTON_SECONDARY_BORDER: DIM_BLACK_8,
  BUTTON_SECONDARY_BORDER_DARK: DIM_BLACK_15,
};

export const DARK_THEME_COLORS: APP_COLORS = {
  TEXT: WHITE,
  BACKGROUND: BLACK,
  TAB_BAR_BACKGROUND: CHARCOAL_900,
  TAB_BAR_FOREGROUND: CHARCOAL_700,
  TINT: WHITE,
  TAB_ICON_DEFAULT: GRAY_300,
  TAB_ICON_SELECTED: WHITE,
  DISABLED: CHARCOAL_800,
  DISABLED_TEXT: GRAY_400,
  DIM: DIM_WHITE_8,
  ICON: GRAY_400,
  FOREGROUND: WHITE,
  CARD: CHARCOAL_900,
  CARD_FOREGROUND: WHITE,
  POPOVER: CHARCOAL_900,
  POPOVER_FOREGROUND: WHITE,
  PRIMARY: PINK,
  PRIMARY_FOREGROUND: WHITE,
  SECONDARY: CHARCOAL_800,
  SECONDARY_FOREGROUND: GRAY_600,
  MUTED: CHARCOAL_900,
  MUTED_FOREGROUND: GRAY_400,
  ACCENT: CHARCOAL_800,
  ACCENT_FOREGROUND: WHITE,
  DESTRUCTIVE: RED_400,
  DESTRUCTIVE_FOREGROUND: WHITE,
  BORDER: CHARCOAL_900,
  BORDER_DARKER: CHARCOAL_700,
  INPUT: CHARCOAL_800,
  INPUT_BACKGROUND: CHARCOAL_900,
  SWITCH_BACKGROUND: GRAY_750,
  RING: PINK,
  CHART_1,
  CHART_2,
  CHART_3,
  CHART_4,
  CHART_5,
  SIDEBAR: BLACK,
  SIDEBAR_FOREGROUND: WHITE,
  SIDEBAR_PRIMARY: PINK,
  SIDEBAR_PRIMARY_FOREGROUND: WHITE,
  SIDEBAR_ACCENT: CHARCOAL_900,
  SIDEBAR_ACCENT_FOREGROUND: WHITE,
  SIDEBAR_BORDER: CHARCOAL_800,
  SIDEBAR_RING: PINK,
  BUTTON_PRIMARY_BACKGROUND: PINK,
  BUTTON_PRIMARY_BACKGROUND_DARK: RED_400,
  BUTTON_PRIMARY_FOREGROUND: WHITE,
  BUTTON_PRIMARY_BORDER: DIM_WHITE_20,
  BUTTON_SECONDARY_BACKGROUND: DIM_WHITE_8,
  BUTTON_SECONDARY_BACKGROUND_DARK: DIM_WHITE_20,
  BUTTON_SECONDARY_FOREGROUND: WHITE,
  BUTTON_SECONDARY_BORDER: DIM_WHITE_20,
  BUTTON_SECONDARY_BORDER_DARK: WHITE,
};

export const COLOR_THEMES: { light: APP_COLORS; dark: APP_COLORS } = {
  light: LIGHT_THEME_COLORS,
  dark: DARK_THEME_COLORS,
};
